import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import VideoPlayer from "@/components/VideoPlayer";
import ListContent from "@/components/ListContent";
import AboutResult from "@/components/AboutResult";
import CombinedComponent from "@/components/CombinedComponent";
import StickyButton from "@/components/StickyButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CombinedComponent />
        <VideoPlayer />
        <ListContent />
        <AboutResult />
        <StickyButton />
        {children}
      </body>
    </html>
  );
}
